# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 19:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('position_lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта')),
                ('position_long', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Довгота')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва')),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('date_of_delivery', models.DateTimeField(verbose_name='Необхідно виконати маршрут до:')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Place', verbose_name='Місце')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position_lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта')),
                ('position_long', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Довгота')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Номеру повинен бути виду +380000000000.', regex='\\+?380?\\d{9}$')], verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User', verbose_name='Користувач'),
        ),
    ]
