# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршрути'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AddField(
            model_name='tracker',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 5, 25, 15, 2, 53, 38621, tzinfo=utc), max_length=500, verbose_name='Опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='place',
            name='position_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='position_long',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='date_of_delivery',
            field=models.DateTimeField(verbose_name='Необхідно виконати маршрут до:'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Place', verbose_name='Місце'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_long',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Довгота'),
        ),
    ]
