# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0004_auto_20160531_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_called', models.BooleanField(default=False)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Tracker', verbose_name='Марштрут')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User', verbose_name='Користувач')),
            ],
        ),
    ]
